// Automatically generated by scripts/generate-manifest.ts
// Do not edit this file manually.

// Pre-compiled Regexes for maximum performance on Cloudflare Workers
export const ROUTE_REGEXPS: Array<RegExp> = [
  /^\/$/,
  /^\/admin\/?$/,
  /^\/banned\/?$/,
  /^\/admin\/posts\/?$/,
  /^\/forgot-password\/?$/,
  /^\/login\/?$/,
  /^\/register\/?$/,
  /^\/reset-link\/?$/,
  /^\/verify-email\/?$/,
  /^\/friend-links\/?$/,
  /^\/posts\/?$/,
  /^\/search\/?$/,
  /^\/unsubscribe\/?$/,
  /^\/membership\/?$/,
  /^\/profile\/?$/,
  /^\/submit-friend-link\/?$/,
  /^\/oauth\/consent\/?$/,
  /^\/post\/[^/]+\/?$/,
  /^\/admin\/users\/[^/]+\/?$/,
  /^\/admin\/card-keys\/?$/,
  /^\/admin\/categories\/?$/,
  /^\/admin\/comments\/?$/,
  /^\/admin\/download-logs\/?$/,
  /^\/admin\/friend-links\/?$/,
  /^\/admin\/logs\/?$/,
  /^\/admin\/media\/?$/,
  /^\/admin\/membership\/?$/,
  /^\/admin\/nav-menu\/?$/,
  /^\/admin\/points-log\/?$/,
  /^\/admin\/points-settings\/?$/,
  /^\/admin\/popup\/?$/,
  /^\/admin\/purchase-orders\/?$/,
  /^\/admin\/settings\/?$/,
  /^\/admin\/tags\/?$/,
  /^\/admin\/template-settings\/?$/,
  /^\/admin\/users\/?$/,
  /^\/admin\/posts\/edit\/[^/]+\/?$/,
];

/**
 * Checks if the path matches any valid route.
 * O(n) regex checks, but zero compilation overhead at runtime.
 */
export function isPathValid(path: string): boolean {
  return ROUTE_REGEXPS.some((regex) => regex.test(path));
}
