/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as UserRouteRouteImport } from './routes/_user/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as UserSubmitFriendLinkRouteImport } from './routes/_user/submit-friend-link'
import { Route as UserProfileRouteImport } from './routes/_user/profile'
import { Route as UserMembershipRouteImport } from './routes/_user/membership'
import { Route as PublicUnsubscribeRouteImport } from './routes/_public/unsubscribe'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicPostsRouteImport } from './routes/_public/posts'
import { Route as PublicFriendLinksRouteImport } from './routes/_public/friend-links'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetLinkRouteImport } from './routes/_auth/reset-link'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AdminPostsRouteRouteImport } from './routes/admin/posts/route'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTemplateSettingsIndexRouteImport } from './routes/admin/template-settings/index'
import { Route as AdminTagsIndexRouteImport } from './routes/admin/tags/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminPurchaseOrdersIndexRouteImport } from './routes/admin/purchase-orders/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminPopupIndexRouteImport } from './routes/admin/popup/index'
import { Route as AdminPointsSettingsIndexRouteImport } from './routes/admin/points-settings/index'
import { Route as AdminPointsLogIndexRouteImport } from './routes/admin/points-log/index'
import { Route as AdminNavMenuIndexRouteImport } from './routes/admin/nav-menu/index'
import { Route as AdminMembershipIndexRouteImport } from './routes/admin/membership/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminLogsIndexRouteImport } from './routes/admin/logs/index'
import { Route as AdminFriendLinksIndexRouteImport } from './routes/admin/friend-links/index'
import { Route as AdminDownloadLogsIndexRouteImport } from './routes/admin/download-logs/index'
import { Route as AdminCommentsIndexRouteImport } from './routes/admin/comments/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminCardKeysIndexRouteImport } from './routes/admin/card-keys/index'
import { Route as AdminUsersIdRouteImport } from './routes/admin/users/$id'
import { Route as PublicPostSlugRouteImport } from './routes/_public/post/$slug'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'

const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSubmitFriendLinkRoute = UserSubmitFriendLinkRouteImport.update({
  id: '/submit-friend-link',
  path: '/submit-friend-link',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserMembershipRoute = UserMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => UserRouteRoute,
} as any)
const PublicUnsubscribeRoute = PublicUnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPostsRoute = PublicPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFriendLinksRoute = PublicFriendLinksRouteImport.update({
  id: '/friend-links',
  path: '/friend-links',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetLinkRoute = AuthResetLinkRouteImport.update({
  id: '/reset-link',
  path: '/reset-link',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminPostsRouteRoute = AdminPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTemplateSettingsIndexRoute =
  AdminTemplateSettingsIndexRouteImport.update({
    id: '/template-settings/',
    path: '/template-settings/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminTagsIndexRoute = AdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPurchaseOrdersIndexRoute =
  AdminPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)
const AdminPopupIndexRoute = AdminPopupIndexRouteImport.update({
  id: '/popup/',
  path: '/popup/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPointsSettingsIndexRoute =
  AdminPointsSettingsIndexRouteImport.update({
    id: '/points-settings/',
    path: '/points-settings/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminPointsLogIndexRoute = AdminPointsLogIndexRouteImport.update({
  id: '/points-log/',
  path: '/points-log/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNavMenuIndexRoute = AdminNavMenuIndexRouteImport.update({
  id: '/nav-menu/',
  path: '/nav-menu/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembershipIndexRoute = AdminMembershipIndexRouteImport.update({
  id: '/membership/',
  path: '/membership/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsIndexRoute = AdminLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFriendLinksIndexRoute = AdminFriendLinksIndexRouteImport.update({
  id: '/friend-links/',
  path: '/friend-links/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDownloadLogsIndexRoute = AdminDownloadLogsIndexRouteImport.update({
  id: '/download-logs/',
  path: '/download-logs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsIndexRoute = AdminCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCardKeysIndexRoute = AdminCardKeysIndexRouteImport.update({
  id: '/card-keys/',
  path: '/card-keys/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicPostSlugRoute = PublicPostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any).lazy(() =>
  import('./routes/_public/post/$slug.lazy').then((d) => d.Route),
)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/banned': typeof BannedRoute
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/friend-links': typeof PublicFriendLinksRoute
  '/posts': typeof PublicPostsRoute
  '/search': typeof PublicSearchRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/membership': typeof UserMembershipRoute
  '/profile': typeof UserProfileRoute
  '/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin/': typeof AdminIndexRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/card-keys/': typeof AdminCardKeysIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/download-logs/': typeof AdminDownloadLogsIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/logs/': typeof AdminLogsIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/membership/': typeof AdminMembershipIndexRoute
  '/admin/nav-menu/': typeof AdminNavMenuIndexRoute
  '/admin/points-log/': typeof AdminPointsLogIndexRoute
  '/admin/points-settings/': typeof AdminPointsSettingsIndexRoute
  '/admin/popup/': typeof AdminPopupIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/purchase-orders/': typeof AdminPurchaseOrdersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/template-settings/': typeof AdminTemplateSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/banned': typeof BannedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-link': typeof AuthResetLinkRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/friend-links': typeof PublicFriendLinksRoute
  '/posts': typeof PublicPostsRoute
  '/search': typeof PublicSearchRoute
  '/unsubscribe': typeof PublicUnsubscribeRoute
  '/membership': typeof UserMembershipRoute
  '/profile': typeof UserProfileRoute
  '/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin': typeof AdminIndexRoute
  '/post/$slug': typeof PublicPostSlugRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/card-keys': typeof AdminCardKeysIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/comments': typeof AdminCommentsIndexRoute
  '/admin/download-logs': typeof AdminDownloadLogsIndexRoute
  '/admin/friend-links': typeof AdminFriendLinksIndexRoute
  '/admin/logs': typeof AdminLogsIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/membership': typeof AdminMembershipIndexRoute
  '/admin/nav-menu': typeof AdminNavMenuIndexRoute
  '/admin/points-log': typeof AdminPointsLogIndexRoute
  '/admin/points-settings': typeof AdminPointsSettingsIndexRoute
  '/admin/popup': typeof AdminPopupIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/purchase-orders': typeof AdminPurchaseOrdersIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tags': typeof AdminTagsIndexRoute
  '/admin/template-settings': typeof AdminTemplateSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_user': typeof UserRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/banned': typeof BannedRoute
  '/admin/posts': typeof AdminPostsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-link': typeof AuthResetLinkRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/friend-links': typeof PublicFriendLinksRoute
  '/_public/posts': typeof PublicPostsRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/unsubscribe': typeof PublicUnsubscribeRoute
  '/_user/membership': typeof UserMembershipRoute
  '/_user/profile': typeof UserProfileRoute
  '/_user/submit-friend-link': typeof UserSubmitFriendLinkRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/post/$slug': typeof PublicPostSlugRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/card-keys/': typeof AdminCardKeysIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/download-logs/': typeof AdminDownloadLogsIndexRoute
  '/admin/friend-links/': typeof AdminFriendLinksIndexRoute
  '/admin/logs/': typeof AdminLogsIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/membership/': typeof AdminMembershipIndexRoute
  '/admin/nav-menu/': typeof AdminNavMenuIndexRoute
  '/admin/points-log/': typeof AdminPointsLogIndexRoute
  '/admin/points-settings/': typeof AdminPointsSettingsIndexRoute
  '/admin/popup/': typeof AdminPopupIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/purchase-orders/': typeof AdminPurchaseOrdersIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tags/': typeof AdminTagsIndexRoute
  '/admin/template-settings/': typeof AdminTemplateSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/banned'
    | '/admin/posts'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/friend-links'
    | '/posts'
    | '/search'
    | '/unsubscribe'
    | '/membership'
    | '/profile'
    | '/submit-friend-link'
    | '/oauth/consent'
    | '/admin/'
    | '/post/$slug'
    | '/admin/users/$id'
    | '/admin/card-keys/'
    | '/admin/categories/'
    | '/admin/comments/'
    | '/admin/download-logs/'
    | '/admin/friend-links/'
    | '/admin/logs/'
    | '/admin/media/'
    | '/admin/membership/'
    | '/admin/nav-menu/'
    | '/admin/points-log/'
    | '/admin/points-settings/'
    | '/admin/popup/'
    | '/admin/posts/'
    | '/admin/purchase-orders/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/template-settings/'
    | '/admin/users/'
    | '/admin/posts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banned'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-link'
    | '/verify-email'
    | '/friend-links'
    | '/posts'
    | '/search'
    | '/unsubscribe'
    | '/membership'
    | '/profile'
    | '/submit-friend-link'
    | '/oauth/consent'
    | '/admin'
    | '/post/$slug'
    | '/admin/users/$id'
    | '/admin/card-keys'
    | '/admin/categories'
    | '/admin/comments'
    | '/admin/download-logs'
    | '/admin/friend-links'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/membership'
    | '/admin/nav-menu'
    | '/admin/points-log'
    | '/admin/points-settings'
    | '/admin/popup'
    | '/admin/posts'
    | '/admin/purchase-orders'
    | '/admin/settings'
    | '/admin/tags'
    | '/admin/template-settings'
    | '/admin/users'
    | '/admin/posts/edit/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_user'
    | '/admin'
    | '/banned'
    | '/admin/posts'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-link'
    | '/_auth/verify-email'
    | '/_public/friend-links'
    | '/_public/posts'
    | '/_public/search'
    | '/_public/unsubscribe'
    | '/_user/membership'
    | '/_user/profile'
    | '/_user/submit-friend-link'
    | '/oauth/consent'
    | '/_public/'
    | '/admin/'
    | '/_public/post/$slug'
    | '/admin/users/$id'
    | '/admin/card-keys/'
    | '/admin/categories/'
    | '/admin/comments/'
    | '/admin/download-logs/'
    | '/admin/friend-links/'
    | '/admin/logs/'
    | '/admin/media/'
    | '/admin/membership/'
    | '/admin/nav-menu/'
    | '/admin/points-log/'
    | '/admin/points-settings/'
    | '/admin/popup/'
    | '/admin/posts/'
    | '/admin/purchase-orders/'
    | '/admin/settings/'
    | '/admin/tags/'
    | '/admin/template-settings/'
    | '/admin/users/'
    | '/admin/posts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  UserRouteRoute: typeof UserRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BannedRoute: typeof BannedRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/submit-friend-link': {
      id: '/_user/submit-friend-link'
      path: '/submit-friend-link'
      fullPath: '/submit-friend-link'
      preLoaderRoute: typeof UserSubmitFriendLinkRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_user/membership': {
      id: '/_user/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof UserMembershipRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/_public/unsubscribe': {
      id: '/_public/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof PublicUnsubscribeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/posts': {
      id: '/_public/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PublicPostsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/friend-links': {
      id: '/_public/friend-links'
      path: '/friend-links'
      fullPath: '/friend-links'
      preLoaderRoute: typeof PublicFriendLinksRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reset-link': {
      id: '/_auth/reset-link'
      path: '/reset-link'
      fullPath: '/reset-link'
      preLoaderRoute: typeof AuthResetLinkRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/template-settings/': {
      id: '/admin/template-settings/'
      path: '/template-settings'
      fullPath: '/admin/template-settings/'
      preLoaderRoute: typeof AdminTemplateSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tags/': {
      id: '/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof AdminTagsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/purchase-orders/': {
      id: '/admin/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/admin/purchase-orders/'
      preLoaderRoute: typeof AdminPurchaseOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
    '/admin/popup/': {
      id: '/admin/popup/'
      path: '/popup'
      fullPath: '/admin/popup/'
      preLoaderRoute: typeof AdminPopupIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/points-settings/': {
      id: '/admin/points-settings/'
      path: '/points-settings'
      fullPath: '/admin/points-settings/'
      preLoaderRoute: typeof AdminPointsSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/points-log/': {
      id: '/admin/points-log/'
      path: '/points-log'
      fullPath: '/admin/points-log/'
      preLoaderRoute: typeof AdminPointsLogIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nav-menu/': {
      id: '/admin/nav-menu/'
      path: '/nav-menu'
      fullPath: '/admin/nav-menu/'
      preLoaderRoute: typeof AdminNavMenuIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/membership/': {
      id: '/admin/membership/'
      path: '/membership'
      fullPath: '/admin/membership/'
      preLoaderRoute: typeof AdminMembershipIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs/': {
      id: '/admin/logs/'
      path: '/logs'
      fullPath: '/admin/logs/'
      preLoaderRoute: typeof AdminLogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/friend-links/': {
      id: '/admin/friend-links/'
      path: '/friend-links'
      fullPath: '/admin/friend-links/'
      preLoaderRoute: typeof AdminFriendLinksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/download-logs/': {
      id: '/admin/download-logs/'
      path: '/download-logs'
      fullPath: '/admin/download-logs/'
      preLoaderRoute: typeof AdminDownloadLogsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments/': {
      id: '/admin/comments/'
      path: '/comments'
      fullPath: '/admin/comments/'
      preLoaderRoute: typeof AdminCommentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/card-keys/': {
      id: '/admin/card-keys/'
      path: '/card-keys'
      fullPath: '/admin/card-keys/'
      preLoaderRoute: typeof AdminCardKeysIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/post/$slug': {
      id: '/_public/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PublicPostSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminPostsRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetLinkRoute: typeof AuthResetLinkRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetLinkRoute: AuthResetLinkRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicFriendLinksRoute: typeof PublicFriendLinksRoute
  PublicPostsRoute: typeof PublicPostsRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicUnsubscribeRoute: typeof PublicUnsubscribeRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicPostSlugRoute: typeof PublicPostSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicFriendLinksRoute: PublicFriendLinksRoute,
  PublicPostsRoute: PublicPostsRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicUnsubscribeRoute: PublicUnsubscribeRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicPostSlugRoute: PublicPostSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface UserRouteRouteChildren {
  UserMembershipRoute: typeof UserMembershipRoute
  UserProfileRoute: typeof UserProfileRoute
  UserSubmitFriendLinkRoute: typeof UserSubmitFriendLinkRoute
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserMembershipRoute: UserMembershipRoute,
  UserProfileRoute: UserProfileRoute,
  UserSubmitFriendLinkRoute: UserSubmitFriendLinkRoute,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface AdminPostsRouteRouteChildren {
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
}

const AdminPostsRouteRouteChildren: AdminPostsRouteRouteChildren = {
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
}

const AdminPostsRouteRouteWithChildren = AdminPostsRouteRoute._addFileChildren(
  AdminPostsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminPostsRouteRoute: typeof AdminPostsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminCardKeysIndexRoute: typeof AdminCardKeysIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCommentsIndexRoute: typeof AdminCommentsIndexRoute
  AdminDownloadLogsIndexRoute: typeof AdminDownloadLogsIndexRoute
  AdminFriendLinksIndexRoute: typeof AdminFriendLinksIndexRoute
  AdminLogsIndexRoute: typeof AdminLogsIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminMembershipIndexRoute: typeof AdminMembershipIndexRoute
  AdminNavMenuIndexRoute: typeof AdminNavMenuIndexRoute
  AdminPointsLogIndexRoute: typeof AdminPointsLogIndexRoute
  AdminPointsSettingsIndexRoute: typeof AdminPointsSettingsIndexRoute
  AdminPopupIndexRoute: typeof AdminPopupIndexRoute
  AdminPurchaseOrdersIndexRoute: typeof AdminPurchaseOrdersIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTagsIndexRoute: typeof AdminTagsIndexRoute
  AdminTemplateSettingsIndexRoute: typeof AdminTemplateSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPostsRouteRoute: AdminPostsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminCardKeysIndexRoute: AdminCardKeysIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCommentsIndexRoute: AdminCommentsIndexRoute,
  AdminDownloadLogsIndexRoute: AdminDownloadLogsIndexRoute,
  AdminFriendLinksIndexRoute: AdminFriendLinksIndexRoute,
  AdminLogsIndexRoute: AdminLogsIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminMembershipIndexRoute: AdminMembershipIndexRoute,
  AdminNavMenuIndexRoute: AdminNavMenuIndexRoute,
  AdminPointsLogIndexRoute: AdminPointsLogIndexRoute,
  AdminPointsSettingsIndexRoute: AdminPointsSettingsIndexRoute,
  AdminPopupIndexRoute: AdminPopupIndexRoute,
  AdminPurchaseOrdersIndexRoute: AdminPurchaseOrdersIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTagsIndexRoute: AdminTagsIndexRoute,
  AdminTemplateSettingsIndexRoute: AdminTemplateSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  UserRouteRoute: UserRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BannedRoute: BannedRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
